<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Implementing a PWA</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='css/style.css' rel='stylesheet' type='text/css'>
        <link rel="manifest" href="manifest.json">

<!--       /add sw to script tag-->
        <script>
            // register the SW
            if ('serviceWorker' in navigator) {
                // navigator.serviceWorker.register('/serviceworker.js',{scope: './'})
                navigator.serviceWorker.register('/serviceworker.js')
                    .then(function(registration) {
                        console.log('ServiceWorker Registration Successful')
                    }).catch(function(error) {
                    console.log('ServiceWorker Registration failed:', error)
                });
            } else {
                console.log('ServiceWorker not supported')
            }
        </script>

    </head>
    <body>

        <div class="container_main">
            <h1>Completed Todo's</h1>
                <div class="todos">
                    <?php
                    foreach($done as $todo) {
                        if (!empty($todo[1])) {
                            echo '<div class="todo">' . $todo[1] . '</div>';
                        }
                    }
                    ?>
                </div>
                
            <br><br>
            <a href="/">Back to Todo's</a>

        </div>

    </body>
</html>
