<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>ToDo App Implemented as a PWA</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='css/style.css' rel='stylesheet' type='text/css'>
        <script defer src="js/app.js"></script>
        <script src="js/localforage.js"></script>
        <link rel="shortcut icon" href="images/icons/favicon.ico" type="image/x-icon">
        <link rel="icon" href="images/icons/favicon.ico" type="image/x-icon">
        <link rel="manifest" href="manifest.json">

        <script>
            // register the SW
        if ('serviceWorker' in navigator) {
            // navigator.serviceWorker.register('/serviceworker.js',{scope: './'})
            navigator.serviceWorker.register('/serviceworker.js')
            .then(function(registration) {
                console.log('ServiceWorker Registration Successful')
            }).catch(function(error) {
                console.log('ServiceWorker Registration failed:', error)
            });
            } else {
            console.log('ServiceWorker not supported')
        }
        </script>

    </head>
    <body>
        
        <div class="container_main">
            <h1>Todo's</h1>

            <h2>ToDo App Implemented as a PWA</h2>
                <div class="offline">
                </div>

                <div class="todos">
                </div>

                <div class="add">
                    <input type="text" name="todo">
                    <button>Add</button>
                </div>
                
            <h2><a href="/done">View Completed Todo's</a></h2>
        </div>

    </body>
</html>
