<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Implementing a PWA</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='css/style.css' rel='stylesheet' type='text/css'>
        <script defer src="js/app.js"></script>
        <script src="js/localforage.js"></script>
        <link rel="shortcut icon" href="images/icons/favicon.ico" type="image/x-icon">
        <link rel="icon" href="images/icons/favicon.ico" type="image/x-icon">
    </head>
    <body>
        <h1>Todo's</h1>
        <div class="offline"></div>
        <div class="todos"></div>
        <div class="add">
            <input type="text" name="todo">
            <button>Add</button>
        </div>
        <br><br>
        <a href="/done">Done Todo's</a>
    </body>
</html>
